import './globals.css'
import {Inter} from 'next/font/google'
import Image from "next/image";

const inter = Inter({subsets: ['latin']})

// These styles apply to every route in the application
import './globals.css'
import Navbar from "@/components/navbar/navbar";
import MobileNavbar from "@/components/mobile-navbar/mobile-navbar";
import CacheProvider from "@/provider/cache-provider";

export const metadata = {
    title: 'Baltic Studios',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    return (
        <CacheProvider>
        <html lang="de">
        <body className={`bg-black text-white ${inter.className}`}>

        <header className="bg-transparent w-full">
            <Navbar></Navbar>
            <MobileNavbar></MobileNavbar>
        </header>
        {children}

        <footer>
        <div
            className="bg-gradient-radial-top overflow-hidden bg-no-repeat p-10 xl:p-16 pb-36 h-footer origin-top to-[#010203]/30 via-[#566fcc]/10 via-[#566fcc]/10 from-[#566fcc]/20 border-[#303545] border-t">

            <div className="grid xl:grid-cols-4 grid-cols-2 mx-auto gap-x-4 w-4/5 justify-items-center pt-10 py-38">
                <div className="h-fit">
                    <Image width={200} height={100} alt="lol" src="/assets/logo.png"/>
                    <p className="text-gray-600 text-sm mt-3">Dieses Projekt steht in keiner Verbindung mit Disney® und
                        deren Marken</p>

                    <div className="flex justify-between px-4 bg-transparent text-white">
                        <div className="py-6 flex">
                            <div className="hidden xl:flex items-center space-x-5">
                                <a className="flex hover:text-gray-200" href="#">
                                    <Image width={25} height={25} alt="lol" src="assets/images/tiktok.svg"
                                           className="h-6 w-6"/>
                                </a>
                                <a className="flex items-center hover:text-gray-200" href="#">
                                    <Image width={25} height={25} alt="lol" src="assets/images/twitter.svg"
                                           className="h-6 w-6"/>
                                </a>

                                <a className="flex items-center hover:text-gray-200" href="#">
                                    <Image width={25} height={25} alt="lol" src="assets/images/youtube.svg"
                                           className="h-6 w-6"/>
                                </a>

                            </div>
                        </div>
                    </div>
                </div>
                <div className="h-fit">
                    <h2 className="text-gray-200 text-[16px]">BALTIC GALAXY</h2>
                    <ul className="text-gray-500 mt-3">
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Startseite</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Entdecken</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Blog</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Fraktionen</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Spieler Portal</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Wiki</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Mediathek</a></li>
                    </ul>
                </div>
                <div className="h-fit">
                    <h2 className="text-gray-200 text-[16px]">WISSENSWERTES</h2>
                    <ul className="text-gray-500 mt-3">
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Regeln</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Guide</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">FAQ</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Branding</a></li>
                    </ul>
                </div>
                <div className="h-fit">
                    <h2 className="text-gray-200 text-[16px]">BALTIC STUDIOS</h2>
                    <ul className="text-gray-500 mt-3">
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Über uns</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Team</a></li>
                        <li><a href="/" className="hover:text-gray-400 hover:cursor-pointer">Werde Teil von uns</a></li>
                    </ul>
                </div>

            </div>

        </div>


                <div className=" hidden lg:block py-4 px-10 mx-auto w-4/5 rounded-lg shadow bg-black">
                    <div className="grid grid-cols-3 p-5">
                        <div>
                            <Image width={200} height={100} alt="lol" src="/assets/logo-studios.webp"/>
                        </div>
                        <div className="h-fit w-full">
                            <p className="xl:text-xl mt-1 text-[12px] text-gray-300">
                                Ein Universum voller Ideen
                            </p>
                        </div>
                        <div>
                            <ul className="mt-2 list-disc">
                                <li className="inline mx-5">
                                    <a href="/" className="hover:text-gray-400 text-gray-500 hover:cursor-pointer">
                                        Datenschutz
                                    </a>
                                </li>
                                <li className="inline mx-5">
                                    <a href="/" className="hover:text-gray-400 text-gray-500 hover:cursor-pointer">
                                        Impressum
                                    </a>
                                </li>
                                <li className="inline mx-5">
                                    <a href="/" className="hover:text-gray-400 text-gray-500 hover:cursor-pointer">
                                        Nutzungsbedingungen
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <span className="block text-[12px] py-4 text-gray-500 sm:text-center dark:text-gray-400">
                        <p>Copyright © BALTIC STUDIOS 2023</p>
                    </span>
                </div>
        </footer>

    </body>
</html>
        </CacheProvider>
    )
}
